import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error": "#ffffff",
        tertiary: "#3e2400",
        outline: "#757682",
        "on-surface": "#0b1c30",
        "on-primary-container": "#90a8ff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "outline-variant": "#c5c5d3",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb8",
        "on-background": "#0b1c30",
        primary: "#00236f",
        "on-tertiary-fixed": "#2a1700",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#00164e",
        error: "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#b6c4ff",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#ef9900",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-fixed-dim": "#4edea3",
        "primary-container": "#1e3a8a",
        "tertiary-container": "#5c3800",
        surface: "#f8f9ff",
        secondary: "#006c49",
        "secondary-fixed": "#6ffbbe",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#264191",
        "surface-variant": "#d3e4fe",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#00714d",
        "surface-tint": "#4059aa",
        background: "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#653e00",
        "on-surface-variant": "#444651",
        "surface-container": "#e5eeff",
        "primary-fixed": "#dce1ff",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-md": "16px",
        "container-max": "1280px",
        base: "4px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "title-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "display-lg": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
